apiVersion: v1
kind: ConfigMap
metadata:
  name: doctors
data:
  details.txt: |-
    Fatima Jamal

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: doctors
      containers:
      - name: doctors
        image: fatimaj/doctors:latest 
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /user/details.txt
          subPath: details.txt
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: doctors
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
